### ISSUE TITLE
is this working?

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire-seedbox-daemon#1]
I tried to find the files that are seeded with seedbox-daemon from muwire, they cant be found.

**Comment by zlatinb** [comment]
The seedbok daemon does not have the ability to import a `connections.txt` file so it relies on a central bootstrap server to connect to the muwire network.  Since there is no such server running right now, it will simply sit disconnected.

What you can do is copy the `h2.*` files from your muwire settings directory to the settings directory of the daemon, that way it should connect.

**Comment by JamesOlvertone** [comment]
Ok, I see. Thats why seedbox tried always to connect to the two same addresses, probably the addresses from CacheServers.groovy

I did what you said and it works now, thank you.

Is there a way to run my own cache server?

**Comment by zlatinb** [comment]
You can run your own cache server and it is easy, here are [instructions](https://github.com/zlatinb/muwire/wiki/MuWire-HostCache)

However, unless the B64 address of your server is added to `CacheServers.groovy` nobody will be able to find it and it in turn will not be able to find anybody.

**Comment by JamesOlvertone** [comment]
Aha ok, I see. That means let it run forever and hope there are always enough known users in the muwirenet.

Thx for your help.
